### ISSUE TITLE
How to request for a cropped image. the following is not working.

### ISSUE THREAD

**Issue by rgogada** [snowzach/doods2#126]
I am trying to get a cropped image of a detection but the following is not working. Could you let me know what I am doing wrong? Thanks.

```
image_processing:
  - platform: doods
    scan_interval: 10000
    url: "http://192.168.1.10:8140"
    timeout: 60
    detector: pytorch
    area: 
      top: 0.8
      left: 0.45
      bottom: 0.4
      right: 0.55
      covers: false
    separate_detections: true ## added these two lines for cropping 
    crop: true                            ## added these two lines for cropping 
    source:
      - entity_id: camera.192_168_1_49 #frontyard
    file_out:
      - "/media/photo/{{ states[camera_entity].name.lower() }}/{{ states[camera_entity].name.lower() }}-latest.jpg"
      #- "/config/www/images/doods/{{ camera_entity.split('.')[1] }}_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
    confidence: 50
    labels:
      - person
```
