### ISSUE TITLE
Problems with detection areas and multiple image_processing pipelines

### ISSUE THREAD

**Issue by eugemaf** [snowzach/doods2#22]
I’m facing some problems with a configuration with 2 image_processing pipelines activated with doods2, using the same detector. 
The problem is related to the detection area definition: if I define a  detection area for each image_processing only the first one works, while the other pipeline is stopped (no detection at all on the second image_processing pipeline).

This is my configuration (extract): 

```
image_processing:
  - platform: doods
    scan_interval: 2
    url: !secret DOODS_url 
    timeout: 10
    detector: mydetector
    source:
      - entity_id: camera.cam_one
    file_out:
      - "/config/www/{{ camera_entity.split('.')[1] }}_latest.jpg"
    area:
      top:    0.3
      left:   0.05
      bottom: 1.0
      right:  0.95 
      
  - platform: doods
    scan_interval: 2
    url: !secret DOODS_url
    timeout: 10
    detector: mydetector
    source:
      - entity_id: camera.cam_two
    file_out:
      - "/config/www/{{ camera_entity.split('.')[1] }}_latest.jpg"
    confidence: 30
    area:
      top:    0.2
      left:   0.1
      bottom: 0.9
      right:  0.95 

    labels:
    - name: MYLABEL_1
    - name: MYLABEL_2
    - name: MYLABEL_3

```

May be there is an error in the configuration file... but I cannot see it.

Anyway without any area definition the two pipelines work correctly.... (i.e. DOODS2 rocks!)

Thank you for your precious help!
