### ISSUE TITLE
Label filtering not working with pytorch

### ISSUE THREAD

**Issue by nvx** [snowzach/doods2#29]
I switched over from doods1 to doods2 using the Home Assistant plugin. I also decided to check out pytorch.

I noticed after scanning the image though that it detected a "bench" in the image, when that isn't list of labels configured in the doods image processing configuration.

**Comment by snowzach** [comment]
Can you share you hass config for doods?

**Comment by nvx** [comment]
> Can you share you hass config for doods?

```
image_processing:
  - platform: doods
    scan_interval: 10000
    url: http://x.x.x.x
    timeout: 60
    detector: pytorch
    source:
      - entity_id: camera.uvc_driveway
    file_out:
      - "/local/{{ camera_entity.split('.')[1] }}_latest.jpg"
    labels:
      - name: person
        confidence: 55
      - car
      - truck
      - bus
      - motorcycle
      - bicycle
      - cat
      - dog
```

**Comment by snowzach** [comment]
This issue is actually with the hass addon and not doods. Can you try setting a global confidence for everything but person? I would say 30-40 probably makes sense. That might be the issue.

**Comment by nvx** [comment]
By global confidence do you mean this:

```
image_processing:
  - platform: doods
    scan_interval: 10000
    url: http://doods.service.consul.nv.io:8421
    timeout: 60
    detector: pytorch
    source:
      - entity_id: camera.uvc_driveway
    file_out:
      - "/local/{{ camera_entity.split('.')[1] }}_latest.jpg"
    confidence: 40
    labels:
      - name: person
        confidence: 55
      - car
      - truck
      - bus
      - motorcycle
      - bicycle
      - cat
      - dog
```

If so note that didn't work. Of note the confidence for bench is actually 82% so above that threshold. The issue is of course that what it's identifying as a bench is actually a set of wooden pailings used for partial privacy and shade. I can see why it's making that mistake, but yeah there's no value in it identifying benches in this context hence trying to disable it.

**Comment by nvx** [comment]
I've also given this a shot too but no dice:

```
image_processing:
  - platform: doods
    scan_interval: 10000
    url: http://x.x.x.x
    timeout: 60
    detector: pytorch
    source:
      - entity_id: camera.uvc_driveway
    file_out:
      - "/local/{{ camera_entity.split('.')[1] }}_latest.jpg"
    labels:
      - name: person
        confidence: 55
      - name: car
        confidence: 30
      - name: truck
        confidence: 30
      - name: bus
        confidence: 30
      - name: motorcycle
        confidence: 30
      - name: bicycle
        confidence: 30
      - name: cat
        confidence: 30
      - name: dog
        confidence: 30
```
