### ISSUE TITLE
Does DOODs 2 support buffering of requests

### ISSUE THREAD

**Issue by karthikvsamy** [snowzach/doods2#36]
Hi,
I am new user to DOODs. Thanks for your work, it really helps
I am not sure whether I can post my query here. 
I use two Raspberry Pis, one running image capture from IP camera and make request to another Pi which runs DOODs server.
DOODs running in docker,
My question is whether DOODs support buffer requests and process (Async) or requesting entity has to wait until receive response for request?
I couldn't solution or support about buffering requests (Async), so please guide me if it is feasible

Thanks
Karthik

**Comment by snowzach** [comment]
Hi, depending on what detector you use, it will allow you to make multiple requests at the same time. On a Raspberry Pi it  may not make a lot of sense to do it though. Running object detection takes a lot of resources. I am not sure if you've looked at the readme but you can actually give DOODS an RTSP URL and listen via a websocket. DOODS will run as fast as it can and feed you data. You can run this multiple times against multiple cameras and it will do its best. That's the way I would recommend if you are hoping to continuously run detections. Other than that, I would probably only run one detection at a time. If you are trying to run detection on every frame it will never be able to keep up. It's okay to say have multiple camera streams but as long as each one is waiting for it to return before sending the next frame, it will do it's best.

**Comment by karthikvsamy** [comment]
Setup
1. Pi 4Gb  (Home Assistant)
2. Pi 2Gb (DOODs) 
One running Home Assistant and other one running DOODs. There are 3 IP Camera that were monitored for motion detection (PIR based).
It times motion gets detected in multiple camera's at once and I feel home assistant is requesting one image processing and it gets blocked until it completes, due to this it misses to capture another frame and process it. 
I would like to know whether anyway I can unblock home assistant from sync call to async call, so that DOODs will queue and process at its own speed. I don't have any timing requirement at which DOODs completes the processing.
Let me know if you need any further detail to help you understand my problem statement

**Comment by karthikvsamy** [comment]
Following is my image processing configuration . I have modified it as per your suggestion to create individual image_processing for each camera and it looks like working for now. Yet to monitor for some more time whether it encounter any error. I will post the update

```
image_processing:
  - platform: doods
    scan_interval: 10000
    url: "http://192.168.0.5:8080"
    timeout: 60
    #detector: default
    detector: tensorflow
    source:
      - entity_id: camera.FileCam1
      - entity_id: camera.FileCam2
      - entity_id: camera.FileCam3
    file_out:
      - "/tmp/{{ camera_entity.split('.')[1] }}_latest.jpg"
      - "/tmp/{{ camera_entity.split('.')[1] }}-{{ now().strftime('%Y%m%d-%H%M%S') }}.jpg"
    confidence: 50
    area:
      covers: false
    labels:
      - name: person
        confidence: 75
        area:
          covers: false
```
