### ISSUE TITLE
MQTT stop working

### ISSUE THREAD

**Issue by MarkStephan89** [snowzach/doods2#54]
Hi, 
doods2 works great :)
But after a few time/detections it do not send to the MQTT server. 

Here my config file: 
```
server:
  host: 0.0.0.0
  port: 8080
  metrics: true
doods:
  log: detections
  boxes:
    enabled: True
    boxColor: [0, 255, 0]
    boxThickness: 1
    fontScale: 1.2
    fontColor: [0, 255, 0]
    fontThickness: 1
  regions:
    enabled: True
    boxColor: [255, 0, 255]
    boxThickness: 1
    fontScale: 1.2
    fontColor: [255, 0, 255]
    fontThickness: 1
  globals:
    enabled: True
    fontScale: 1.2
    fontColor: [255, 255, 0]
    fontThickness: 1
  detectors:
    - name: default
      type: tflite
      modelFile: models/coco_ssd_mobilenet_v1_1.0_quant.tflite
      labelFile: models/coco_labels0.txt
mqtt:
  metrics: true
  broker: 
    host: "xxx.xxx.xxx.xxx"
    #port: 1883
    #user: "username"
    #password: "password"
  requests:
    - id: ipcam1
      detector_name: default
      preprocess: []
      data: b64
      image: jpeg
      throttle: 2
      separate_detections: true
      crop: false
      binary_images: false
      detect:
        "person": 50
      regions:
      - top: 0
        left: 0
        bottom: 0
        right: 0
        detect:
          "person": 50
        covers: false
      data: rtsp://xxx:xxx@cam:554/11
```

and the docker-compose file: 

```
version: "3.6"
services:
  doods2:
    command:
      - mqtt
    container_name: doods2
    entrypoint:
      - python3
      - main.py
    environment:
      - CONFIG_FILE=xxx.yaml
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - DEBIAN_FRONTEND=noninteractive
      - LANG=C.UTF-8
      - TF_CPP_MIN_LOG_LEVEL=3
      - TZ=Europe/Berlin
    image: snowzach/doods2:latest
    ports:
      - 8010:8080/tcp
    volumes:
      - ./xxx.yaml:/opt/doods/xxx.yaml
```

in the docker logs I can see the detections, so the detections are ok, only the mqtt connection is not functional. 

Thanks!
