### ISSUE TITLE
boxes, regions & globals settings have no effect

### ISSUE THREAD

**Issue by v0d0r** [snowzach/doods2#82]
I am quite enjoying doods thanks.  Its super light weight and fast even on a Odroid SBC.
I am however having one problem.
I cannot seem to change the font/text sizes.  I am loading the config file and it applies correctly into docker I can see this as whatever changes I make on the local yaml file is exposed into the dockers volume yaml file.
I then went as far as to make typo's in the file and as expected doods2 fails to start.
Then I unded the typos and just remove the boxes, regions and global sections from the config.  It stills started up fine.
This leads me to believe these settings are not implemented or just ignored or am I just missing something?

See find below in the container showing only 1 config.yaml file as well as the yaml content below with everything commented out and it starts fine. 

root@638a49e49a43:/# find . -iname 'config.yaml'
./opt/doods/config.yaml

root@638a49e49a43:/# cat ./opt/doods/config.yaml
doods:
  detectors:
    - name: default
      type: tflite
      modelFile: models/coco_ssd_mobilenet_v1_1.0_quant.tflite
      labelFile: models/coco_labels0.txt
    - name: tensorflow
      type: tensorflow
      modelFile: models/faster_rcnn_inception_v2_coco_2018_01_28.pb
      labelFile: models/coco_labels1.txt
    - name: pytorch
      type: pytorch
      modelFile: ultralytics/yolov5,yolov5s
root@638a49e49a43:/#

**Comment by snowzach** [comment]
What did you set for color and font?

**Comment by v0d0r** [comment]
I had them as default but then changed them randomly on boxes, globals and regions.
Below was the last values I had but it seemed to have no effect

  boxes:
    enabled: True
    boxColor: [255, 255, 0]
    boxThickness: 10
    fontScale: 2.10
    fontColor: [0, 255, 0]
    fontThickness: 2
  regions:
    enabled: True
    boxColor: [255, 0, 255]
    boxThickness: 10
    fontScale: 2.10
    fontColor: [255, 0, 255]
    fontThickness: 2
  globals:
    enabled: True
    fontScale: 3.10
    fontColor: [255, 255, 0]
    fontThickness: 2

**Comment by snowzach** [comment]
This is the format... Make sure you have the indentation correct...
```
doods:
  boxes:
    enabled: True
    boxColor: [255, 0, 255]
    boxThickness: 10
    fontScale: 2.10
    fontColor: [255, 0, 255]
    fontThickness: 2
  regions:
    enabled: True
    boxColor: [255, 0, 255]
    boxThickness: 10
    fontScale: 2.10
    fontColor: [255, 0, 255]
    fontThickness: 2
  globals:
    enabled: True
    fontScale: 3.10
    fontColor: [255, 255, 0]
    fontThickness: 2
  detectors:
    - name: default
      type: tflite
      modelFile: models/coco_ssd_mobilenet_v1_1.0_quant.tflite
      labelFile: models/coco_labels0.txt
```
