### ISSUE TITLE
Remove Boxes

### ISSUE THREAD

**Issue by jorgemontes** [snowzach/doods2#91]
Hello, I'm using HA OS. I'm trying to remove the boxes from the generated images. My configuration looks like this, but It does not change the generated images. Am i doing something wrong?

```yaml
logger:
  level: info
server:
  port: "8080"
  auth_key: ""
doods.detectors:
  - name: default
    type: tflite
    modelFile: /opt/doods/models/coco_ssd_mobilenet_v1_1.0_quant.tflite
    labelFile: /opt/doods/models/coco_labels0.txt
    hwAccel: false
  - name: tensorflow
    type: tensorflow
    modelFile: /opt/doods/models/faster_rcnn_inception_v2_coco_2018_01_28.pb
    labelFile: /opt/doods/models/coco_labels1.txt
    hwAccel: false
doods.boxes:
  enabled: false
  boxThickness: 0
  ```

**Comment by snowzach** [comment]
Unfortunately, the way HA OS works, it's nearly impossible to configure DOODS right. They mandate how config must be specified and I haven't figure out how to make it work. I actually just checked again a couple weeks ago and they still haven't fixed it. Sorry. :-(

**Comment by snowzach** [comment]
ACTUALLY! I think I figured something out... You can not specify box config. You may need to uninstall and re-install the DOODS2 add-on. You can now configure the boxes.

**Comment by jorgemontes** [comment]
I uninstalled and reinstalled. After checking the new detection it still shows the boxes. I tried using the `enabled` and `boxThickness` parameters. There's no clear way to know the version I reinstalled is the expected one. It just says **Current version: 1** . This is my configuration for boxes:

```yaml
enabled: false
boxColor: "#00ff00"
boxThickness: 0
fontScale: 1.2
fontColor: "#00ff00"
fontThickness: 1
```
