### ISSUE TITLE
Issue with pytorch in a fresh install undefined symbol: cudaGraphDebugDotPrint

### ISSUE THREAD

**Issue by xavierutox** [snowzach/doods2#92]
Hello, recently i tried to pull a fresh image but it is giving me this error:

```doods_1  | Traceback (most recent call last):
doods_1  |   File "main.py", line 8, in <module>
doods_1  |     from doods import Doods
doods_1  |   File "/opt/doods/doods.py", line 20, in <module>
doods_1  |     from detectors.pytorch import PyTorch
doods_1  |   File "/opt/doods/detectors/pytorch.py", line 7, in <module>
doods_1  |     import torch
doods_1  |   File "/usr/local/lib/python3.8/dist-packages/torch/__init__.py", line 229, in <module>
doods_1  |     from torch._C import *  # noqa: F403
doods_1  | ImportError: /usr/local/lib/python3.8/dist-packages/torch/lib/libtorch_cuda.so: undefined symbol: cudaGraphDebugDotPrint, version libcudart.so.11.0
aidocker_doods_1 exited with code 1`
```

This is my docker-compose file:
```
version: '3.2'
services:
  doods:
    image: snowzach/doods2:amd64-gpu
    ports:
      - "8080:8080"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```
