### ISSUE TITLE
Could not create detector, RPi4 (deepstack, pytorch)

### ISSUE THREAD

**Issue by igneon-ha** [snowzach/doods2#96]
Greetings!

I'm having a problem that, based on my research here and on other resources, has already occurred earlier.

Having pulled and run **"latest"** image on **RPi4** I see the following errors in the container log.
Needless to say that all the attempts to use both **pytorch** and **deepstack** models lead to failure.

Could you, please, help with the situation?

_Basic built-in config used for starters:_

```
root@3cdd1427f1f0:/opt/doods# cat config.yaml
doods:
  boxes:
    enabled: True
    boxColor: [0, 255, 0]
    boxThickness: 1
    fontScale: 1.2
    fontColor: [0, 255, 0]
    fontThickness: 1
  regions:
    enabled: True
    boxColor: [255, 0, 255]
    boxThickness: 1
    fontScale: 1.2
    fontColor: [255, 0, 255]
    fontThickness: 1
  globals:
    enabled: True
    fontScale: 1.2
    fontColor: [255, 255, 0]
    fontThickness: 1
  detectors:
    - name: default
      type: tflite
      modelFile: models/coco_ssd_mobilenet_v1_1.0_quant.tflite
      labelFile: models/coco_labels0.txt
    - name: tensorflow
      type: tensorflow
      modelFile: models/faster_rcnn_inception_v2_coco_2018_01_28.pb
      labelFile: models/coco_labels1.txt
    - name: pytorch
      type: pytorch
      modelFile: ultralytics/yolov5,yolov5s
```

_Logs with basic config:_

> root@ubuntu:~# docker logs -f 3cdd1427f1f0
> 2023-11-03 19:13:56,531 - doods.doods - INFO - Registered detector type:tflite name:default
> 2023-11-03 19:14:03,195 - doods.doods - INFO - Registered detector type:tensorflow name:tensorflow
> 2023-11-03 19:14:03,195 - doods.doods - ERROR - **Could not create detector pytorch/pytorch: Unknown detector type pytorch.**
> 2023-11-03 19:14:03,317 - uvicorn.error - INFO - Started server process [1]
> 2023-11-03 19:14:03,318 - uvicorn.error - INFO - Waiting for application startup.
> 2023-11-03 19:14:03,319 - uvicorn.error - INFO - Application startup complete.
> 2023-11-03 19:14:03,320 - uvicorn.error - INFO - Uvicorn running on http://0.0.0.0:8080 

_Config with added **deepstack** directive:_
```
GNU nano 4.8                                                                              config.yaml                                                                               Modified
doods:
  boxes:
    enabled: True
    boxColor: [0, 255, 0]
    boxThickness: 1
    fontScale: 1.2
    fontColor: [0, 255, 0]
    fontThickness: 1
  regions:
    enabled: True
    boxColor: [255, 0, 255]
    boxThickness: 1
    fontScale: 1.2
    fontColor: [255, 0, 255]
    fontThickness: 1
  globals:
    enabled: True
    fontScale: 1.2
    fontColor: [255, 255, 0]
    fontThickness: 1
  detectors:
    - name: default
      type: tflite
      modelFile: models/coco_ssd_mobilenet_v1_1.0_quant.tflite
      labelFile: models/coco_labels0.txt
    - name: tensorflow
      type: tensorflow
      modelFile: models/faster_rcnn_inception_v2_coco_2018_01_28.pb
      labelFile: models/coco_labels1.txt
    - name: pytorch
      type: pytorch
      modelFile: ultralytics/yolov5,yolov5s
    - name: dark
      type: deepstack
      modelFile: models/dark.pt
```

_The log is as follows:_

> root@ubuntu:~# docker logs -f 3cdd1427f1f0
> 2023-11-03 19:13:56,531 - doods.doods - INFO - Registered detector type:tflite name:default
> 2023-11-03 19:14:03,195 - doods.doods - INFO - Registered detector type:tensorflow name:tensorflow
> 2023-11-03 19:14:03,195 - doods.doods - ERROR - Could not create detector pytorch/pytorch: Unknown detector type pytorch.
> 2023-11-03 19:14:03,317 - uvicorn.error - INFO - Started server process [1]
> 2023-11-03 19:14:03,318 - uvicorn.error - INFO - Waiting for application startup.
> 2023-11-03 19:14:03,319 - uvicorn.error - INFO - Application startup complete.
> 2023-11-03 19:14:03,320 - uvicorn.error - INFO - Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
> 2023-11-03 19:34:20,567 - uvicorn.error - INFO - Shutting down
> 2023-11-03 19:34:20,668 - uvicorn.error - INFO - Waiting for application shutdown.
> 2023-11-03 19:34:20,670 - uvicorn.error - INFO - Application shutdown complete.
> 2023-11-03 19:34:20,670 - uvicorn.error - INFO - Finished server process [1]
> 2023-11-03 19:34:29,995 - doods.doods - INFO - Registered detector type:tflite name:default
> 2023-11-03 19:34:36,537 - doods.doods - INFO - Registered detector type:tensorflow name:tensorflow
> 2023-11-03 19:34:36,537 - doods.doods - ERROR - **Could not create detector deepstack/dark: Unknown detector type deepstack.**
> 2023-11-03 19:34:36,537 - doods.doods - ERROR - **Could not create detector pytorch/pytorch: Unknown detector type pytorch.**
> 2023-11-03 19:34:36,655 - uvicorn.error - INFO - Started server process [1]
> 2023-11-03 19:34:36,656 - uvicorn.error - INFO - Waiting for application startup.
> 2023-11-03 19:34:36,657 - uvicorn.error - INFO - Application startup complete.
> 2023-11-03 19:34:36,658 - uvicorn.error - INFO - Uvicorn running on 
> http://0.0.0.0:8080

Tried to run it with no directives but the **deepstack** one - same result.
